# Generated by Django 4.1.3 on 2022-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('main_category', models.CharField(max_length=40)),
                ('last_update', models.DateField()),
            ],
        ),
    ]
