# Generated by Django 4.1.3 on 2022-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date_time', models.DateField()),
                ('home_team_name', models.CharField(max_length=100)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_name', models.CharField(max_length=100)),
                ('away_team_score', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=100)),
                ('status_info', models.CharField(max_length=30)),
                ('prev_results', models.JSONField(default='{}')),
            ],
        ),
    ]
